################################################
#                                              #
#                  Timed Fly                   #
#               Made by By_Jack                #
#                                              #
################################################


#The iventory that shows up when using /fly
Gui:
  #Custom name of the inventory
  DisplayName: TimedFly
  #Rows of the inventory (must be multiple of 9, ex: 9, 18... etc)
  Slots: 9

#Set to true if you want to stop the fly time when the player leaves the server
#so when he joins again it resumes the time left.
SaveTimeLeave: true

#A list of world in which you want the plugin to be enabled.
Enabled-Worlds:
- 'world'
- 'survival'

#The name says it...
Check-For-Updates: true

#Choose your own message file (if file name is lang_en.yml use the work after lang_ in this case will be en
#Current languages es, sp, you can create your own and send it to me so I added for default.
#Is not recomended to use the /tf reload command, some messages will not change.
Lang: en
