main: com.minestom.TimedFly
name: TimedFly
version: 2.3.2
author: By_Jack
depend: [Vault]
softdepend: [PlaceholderAPI, TokenManager, ASkyBlock]
commands:
  timedfly:
    aliases: [tf, timedf]
    usage: /<command>
    description: The main command of TimedFly
  tfly:
    usage: /<command>
    description: Open the fly GUI
