################################################
#                                              #
#                  TimedFly 4                  #
#               Made by By_Jack                #
#                                              #
################################################

# Modes are 'core' or 'complete'.
  # Core will only enable the timer. So, no store
  # Complete will enable everything... store, cooldowns, refunds, etc.
Mode: 'complete'

# Enable this so your players can refund their flight time if they bought it by accident.
Refunds:
  Enable: true
  # The time they have until the refund is valid
  TimeNoRefund: '5m'
  # The amount of refunds players can make a day
  RefundsPerDay: 2

Database:
  # Type: sqlite for flatfile or mysql for an external database.
  Type: 'sqlite'
  # Only edit if 'mysql' is set in Type
  MySQL:
    # name of your database
    Database: 'timedfly'
    # ip of you MySQL database
    Host: 'localhost'
    # port of you MySQL database, commonly is 3306
    Port: 3306
    # username of you MySQL database
    Username: 'user'
    # password of you MySQL database
    Password: 'root'

OpenMenu:
  # If set to true players will need a permission to use the command /fly
  UsePermission:
    Enable: false
    Permission: 'timedfly.flygui'
    # Custom command to open the Timed Fly menu.
    Commands:
      - 'fly'
      - 'flymenu'

Gui:
  Enable: true
  # Custom name of the inventory
  DisplayName: 'TimedFly'
  # Rows of the inventory (must be multiple of 9, ex: 9, 18... etc)
  Slots: 9

StopTimerOn:
  # If true the players time will be saved with the player leaves the server
  Leave: true

  # If true flight will be disabled for the provided time if the player attacks a mob/player.
  Attack:
    Enable: true
    # Disable flight if the player attacks the provided entity. (player, mob, all)
    Entity: 'all'
    Cooldown: '10s'

  # If true flight will be disabled if the player is on the ground.
  Ground: false

  # If true the players time will be saved with the player enters one of the blacklisted worlds
  # Do not use if you are running the plugin with multiple servers liked via MySQL
  BlackListedWorld: false

# If true players with "timedfly.fly.onoff" will toggle flight mode if a command from OpenMenuCommand is used.
ToogleFlight: false

# Set to true if you want to get a message in the console saying who bought flight time.
LogConsoleOnBuy: false

# If true a bossbar will appear when a player buys time (only servers v1.9 and above)
BossBarTimer:
  Enable: false
  Color: green
  Style: SEGMENTED_6

# If true player will join flying if they have some time left.
JoinFlying:
  Enable: true
  # Amount of blocks above the player's location.
  Height: 2

# Set to false if you are lazy and you are using spigot 1.8
Sounds:
  Enable: true
  Announcer: ENTITY_EXPERIENCE_ORB_PICKUP
  FlightDisabled: ENTITY_WITHER_DEATH

# You can enable multiple currency types (Not recommended)
CurrencyType:
  # If true the currency used will be from TokenManager, balance placeholder: [tokens]
  UseTokenManager: false

  # If true the currency used will be from PlayerPoints, balance placeholder: [points]
  UsePlayerPoints: false

  # If true the currency used will be from Vault, balance placeholder: [balance]
  UseVault: true

  # If true players will be charged from their exp levels, balance placeholder: [levels]
  UseLevelsCurrency: false

  # If true players will be charged from their experience points, balance placeholder: [exp]
  UseExpCurrency: false

# This is the limit amount of time a player can add to his fly time (in minutes)
# bypass this with timedfly.limit.bypass.
LimitMaxTime: 30

# Display some messages on Title/Actionbar.
Messages:
  Title: true
  ActionBar: true
  # Announce the time left chosen below to the player (time in seconds)
  Announcer:
    Chat: false
    Titles: true
    Times:
      - '120'
      - '60'
      - '10'
      - '5'
      - '4'
      - '3'
      - '2'
      - '1'
      - '0'


# If true it will execute a command when flight disables
OnFlyDisableCommands:
  Enable: false
  Commands:
    - '[console] say %player% is using hacks D:'
    - '[player] say i''m using hacks >:D'

# A list of world in which you want the plugin to be Enable.
World-List:
  # Available types:
  # enable: the plugin will work in worlds listed
  # disable: the plugin will not work in worlds listed
  # all: the plugin will work in all worlds
  Type: 'all'
  Worlds:
    - 'world'
    - 'survival'

Integrations:
  # If the server is running aSkyBlock and this is true players flight will be disabled when exiting the island
  aSkyblock: true

Check-For-Updates:
  # The name says it...
  Enable: true
  # Auto download new updates
  Auto-Download: false

# Choose your own message file (if file name is lang_en.yml use the work after lang_ in this case will be en
# Current languages es, sp, hu, de, you can create your own and send it to me so I added for default.
Lang: en
