main: com.timedfly.TimedFly
name: TimedFly
version: 3.4.3
author: By_Jack
softdepend: [WorldGuard, PlaceholderAPI, TokenManager, ASkyBlock, Vault, PlayerPoints]
commands:
  timedfly:
    aliases: [tf, timedf]
    usage: /<command>
    description: The main command of TimedFly
  tfly:
    usage: /<command>
    description: Open the fly GUI
